DROP SCHEMA IF EXISTS INFYINTERNS_DB;

CREATE SCHEMA INFYINTERNS_DB;
USE INFYINTERNS_DB;
   
CREATE TABLE MENTOR
(
   MENTOR_ID INT AUTO_INCREMENT, 
   MENTOR_NAME VARCHAR(20) NOT NULL, 
   PROJECTS_MENTORED INT NOT NULL, 
   CONSTRAINT ps_MENTOR_id_pk PRIMARY KEY (MENTOR_ID)
);

CREATE TABLE PROJECT
(
   PROJECT_ID INT AUTO_INCREMENT,    
   PROJECT_NAME VARCHAR(20) NOT NULL, 
   IDEA_OWNER INT NOT NULL, 
   RELEASE_DATE DATE NOT NULL, 
   MENTOR_ID INT REFERENCES MENTOR, 
   CONSTRAINT ps_PROJECT_id_pk PRIMARY KEY (PROJECT_ID)
);

INSERT INTO MENTOR VALUES(1000, 'William', 0);
INSERT INTO MENTOR VALUES(1001, 'John', 1);
INSERT INTO MENTOR VALUES(1002, 'Warner', 3);
INSERT INTO MENTOR VALUES(1003, 'James', 0);
INSERT INTO MENTOR VALUES(1004, 'Allen', 0); 
INSERT INTO MENTOR VALUES(1005, 'Peter', 1); 
INSERT INTO MENTOR VALUES(1006, 'Smith', 1); 
INSERT INTO MENTOR VALUES(1007, 'Chris', 1);
INSERT INTO MENTOR VALUES(1008, 'Alice', 2);
INSERT INTO MENTOR VALUES(1009, 'Bethany', 2);

INSERT INTO PROJECT VALUES(1, 'Shoe Cart', 10012, SYSDATE() + INTERVAL 40 day, 1009);
INSERT INTO PROJECT VALUES(2, 'One-Stop Shop App', 10025, SYSDATE() + INTERVAL 50 day, 1008);
INSERT INTO PROJECT VALUES(3, 'Buy N Sell Portal', 10025, SYSDATE() + INTERVAL 30 day, 1008);
INSERT INTO PROJECT VALUES(4, 'Dine Easy', 10000, SYSDATE() + INTERVAL 20 day, 1006);
INSERT INTO PROJECT VALUES(5, 'Tutor Point', 10012, SYSDATE() + INTERVAL 25 day, 1002);
INSERT INTO PROJECT VALUES(6, 'Elevate', 10000, SYSDATE() + INTERVAL 35 day, 1008);
INSERT INTO PROJECT VALUES(7, 'Health App', 10018, SYSDATE() + INTERVAL 15 day, 1002);
INSERT INTO PROJECT VALUES(8, 'Visitor Portal', 10018, SYSDATE() + INTERVAL 10 day, 1002);
INSERT INTO PROJECT VALUES(9, 'Chatter Box', 10038, SYSDATE() + INTERVAL 5 day, 1005);
INSERT INTO PROJECT VALUES(10, 'Quiz Yourself', 10009, SYSDATE() + INTERVAL 25 day, 1001);
INSERT INTO PROJECT VALUES(11, 'Take a Ride', 10038, SYSDATE() + INTERVAL 10 day, 1009);
INSERT INTO PROJECT VALUES(12, 'BookBay', 10096, SYSDATE() + INTERVAL 10 day, 1007);

COMMIT;

SELECT * FROM MENTOR;
SELECT * FROM PROJECT;